name:                ChptEx
version:             0.1.0.0
github:              "nail82/ChptEx"
license:             BSD3
author:              "Ted Satcher"
maintainer:          "ted.satcher@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nail82/ChptEx#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - checkers
  - QuickCheck

executables:
  ChptEx-exe:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ChptEx

tests:
  ChptEx-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Worphans
    dependencies:
    - ChptEx
    - checkers
    - QuickCheck
