name:                morse
version:             0.1.0.0
github:              "nail82/morse"
license:             BSD3
author:              "Ted Satcher"
maintainer:          "ted.satcher@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Chapter 14 Morse Exercise

dependencies:
- base >= 4.7 && < 5


library:
  source-dirs: src
  exposed-modules: Morse
  dependencies:
  - containers
  - QuickCheck

executables:
  morse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fwarn-tabs
    dependencies:
    - morse

tests:
  morse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse
    - containers
    - QuickCheck
